(function () {
  var header = [
    '<!-- header begin -->',
    '<header class="transparent site-sticky-header fixed header-mobile-sticky">',
    '  <div class="container">',
    '    <div class="row">',
    '      <div class="col-md-12">',
    '        <div class="de-flex sm-pt10">',
    '          <div class="de-flex-col">',
    '            <div id="logo">',
    '              <a href="index.html">',
    '                <span class="logo-main brand-text-logo">Shivansh Square</span>',
    '                <span class="logo-scroll brand-text-logo">Shivansh Square</span>',
    '                <span class="logo-mobile brand-text-logo">Shivansh Square</span>',
    '              </a>',
    '            </div>',
    '          </div>',
    '          <div class="de-flex-col header-col-mid">',
    '            <ul id="mainmenu">',
    '              <li><a class="menu-item" href="index.html">Home</a></li>',
    '              <li><a class="menu-item" href="about.html">About Us</a></li>',
    '              <li><a class="menu-item" href="services-style-3.html">Services</a></li>',
    '              <li><a class="menu-item" href="projects.html">Portfolio</a></li>',
    '              <li><a class="menu-item" href="contact.html">Contact</a></li>',
    '            </ul>',
    '          </div>',
    '          <div class="de-flex-col">',
    '            <div class="menu_side_area">',
    '              <a href="consultation.html" class="btn-main fx-slide"><span>Request A Quote</span></a>',
    '              <span id="menu-btn"></span>',
    '            </div>',
    '            <div id="btn-extra">',
    '              <span></span>',
    '              <span></span>',
    '            </div>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  </div>',
    '</header>',
    '<!-- header close -->'
  ].join('');

  var footer = [
    '<!-- footer begin -->',
    '<footer class="site-footer text-light section-dark">',
    '  <div class="container">',
    '    <div class="site-footer__top">',
    '      <div class="site-footer__brand">',
    '        <a href="index.html">',
    '          <span class="site-footer__logo brand-text-logo">Shivansh Square</span>',
    '        </a>',
    '        <p>',
    '          Shivansh Square delivers turnkey interior, civil, MEP, security,',
    '          networking, HVAC, and workspace solutions designed for modern',
    '          residential and commercial environments.',
    '        </p>',
    '      </div>',
    '      <div class="site-footer__links">',
    '        <h3>Pages</h3>',
    '        <ul>',
    '          <li><a href="index.html">Home</a></li>',
    '          <li><a href="about.html">About Us</a></li>',
    '          <li><a href="services-style-3.html">Services</a></li>',
    '          <li><a href="projects.html">Portfolio</a></li>',
    '          <li><a href="contact.html">Contact</a></li>',
    '        </ul>',
    '      </div>',
    '      <div class="site-footer__links">',
    '        <h3>Services</h3>',
    '        <ul>',
    '          <li><a href="services-style-3.html">Interiors</a></li>',
    '          <li><a href="services-style-3.html">Security Systems</a></li>',
    '          <li><a href="services-style-3.html">Fire-Fighting</a></li>',
    '          <li><a href="services-style-3.html">HVAC & Air-Conditioning</a></li>',
    '          <li><a href="services-style-3.html">Electricals & Networking</a></li>',
    '          <li><a href="services-style-3.html">Work Stations</a></li>',
    '        </ul>',
    '      </div>',
    '      <div class="site-footer__contact">',
    '        <h3>Request A Quote</h3>',
    '        <p>Office No. 501, 5th Floor, Ghanshyam Enclave, New Link Road, Kandivali (West), Mumbai - 400067, Maharashtra - INDIA.</p>',
    '        <p><a href="tel:+919967064755">+91 99670 64755</a></p>',
    '        <a href="consultation.html" class="btn-main fx-slide"><span>Request A Quote</span></a>',
    '        <div class="site-footer__social">',
    '          <a href="#" aria-label="Facebook"><i class="fa-brands fa-facebook-f"></i></a>',
    '          <a href="#" aria-label="Instagram"><i class="fa-brands fa-instagram"></i></a>',
    '          <a href="#" aria-label="YouTube"><i class="fa-brands fa-youtube"></i></a>',
    '          <a href="#" aria-label="WhatsApp"><i class="fa-brands fa-whatsapp"></i></a>',
    '        </div>',
    '      </div>',
    '    </div>',
    '    <div class="site-footer__bottom">',
    '      <div>Copyright 2026 Shivansh Square. All Rights Reserved.</div>',
    '      <div class="site-footer__bottom-links">',
    '        <a href="contact.html">Contact</a>',
    '        <a href="services-style-3.html">Services</a>',
    '      </div>',
    '    </div>',
    '  </div>',
    '</footer>',
    '<!-- footer close -->'
  ].join('');

  function render(id, html) {
    var target = document.getElementById(id);
    if (target && !target.dataset.rendered) {
      target.innerHTML = html;
      target.dataset.rendered = 'true';
    }
  }

  render('site-header', header);
  render('site-footer', footer);
})();
